import { Certificate } from './types';

export const FALLBACK_CERTIFICATES: Certificate[] = [
  {
    "id": "APO-2026-0810-76402",
    "applicantName": "ABDUL WAZED",
    "fatherName": "ABDUL KARIM",
    "motherName": "ROKEYA BEGOM",
    "dob": "1995-05-15",
    "certificateType": "Educational Certificate",
    "examinationName": "HSC Examination",
    "rollNumber": "123456",
    "registrationNumber": "9876543210",
    "certificateNumber": "AP-1786358676402",
    "boardName": "Board of Intermediate and Secondary Education, Dhaka",
    "country": "United Kingdom",
    "issueDate": "2026-08-10",
    "qrCodeDataUrl": "",
    "officerName": "Md. Nazrul Islam",
    "officerDesignation": "Assistant Secretary (Consular)",
    "signatureImageUrl": "",
    "sealImageUrl": "",
    "createdDate": "2026-08-10T04:00:00.000Z",
    "status": "VERIFIED",
    "attachedCertificates": []
  },
  {
    "id": "APO-2026-0810-5472",
    "applicantName": "MOHAMMAD ARMAN HOSSAIN",
    "fatherName": "RUHUL AMIN",
    "motherName": "ROWSHAN ARA BEGUM",
    "dob": "1996-03-12",
    "certificateType": "Educational Certificate",
    "examinationName": "HSC Examination",
    "rollNumber": "654321",
    "registrationNumber": "1234567890",
    "certificateNumber": "AP-1786358650417",
    "boardName": "Board of Intermediate and Secondary Education, Dhaka",
    "country": "United Kingdom",
    "issueDate": "2026-08-10",
    "qrCodeDataUrl": "",
    "officerName": "Md. Nazrul Islam",
    "officerDesignation": "Assistant Secretary (Consular)",
    "signatureImageUrl": "",
    "sealImageUrl": "",
    "createdDate": "2026-08-10T04:00:00.000Z",
    "status": "VERIFIED",
    "attachedCertificates": []
  },
  {
    "id": "BD-AP-2026-95851",
    "applicantName": "ABDUL WAZED",
    "fatherName": "ABDUL KARIM",
    "motherName": "ROKEYA BEGOM",
    "dob": "1995-05-15",
    "certificateType": "Educational Certificate",
    "certificateNumber": "AP-1782126035106",
    "boardName": "Dhaka",
    "country": "United Kingdom",
    "issueDate": "2026-06-22",
    "qrCodeDataUrl": "",
    "officerName": "Md. Nazrul Islam",
    "officerDesignation": "CONTROLLER OF THE EXAMINATION",
    "signatureImageUrl": "",
    "sealImageUrl": "",
    "createdDate": "2026-06-22T11:00:35.106Z",
    "status": "VERIFIED",
    "attachedCertificates": []
  }
];
